name: FlyTranslate
version: '${version}'
main: flyproject.flytranslate.FlyTranslate
softdepend: [ AmazingBot, MiraiMC ]
authors: [ FlyProject ]
description: Translate in qq
commands:
  flytranslate:
    permission: flytranslate.use
  translate:
    permission: flytranslate.use
  transl:
    permission: flytranslate.use
  ftlchatplayersend:
    permission: flytranslate.system
    description: 无功能性作用
permissions:
  flytranslate.use:
    default: true
  flytranslate.system:
    default: op
